FROM node:22.14.0-alpine AS base

# Install pnpm
RUN npm install -g pnpm

# 1. Installation
FROM base AS deps
WORKDIR /app

# Copy package.json and pnpm-lock.yaml
COPY package.json pnpm-lock.yaml ./

# Install dependencies
RUN pnpm install --frozen-lockfile

# 2. Build
FROM base AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .

# Define build arguments
ARG NEXT_PUBLIC_LAUNCHPAD_CHAIN_ID
ARG NEXT_PUBLIC_ALCHEMY_API_KEY
ARG NEXT_PUBLIC_POLYGON_RPC
ARG NEXT_PUBLIC_MAINNET_RPC
ARG NEXT_PUBLIC_ZKSYNC_RPC
ARG NEXT_PUBLIC_BASE_RPC
ARG NEXT_PUBLIC_BASE_SEPOLIA_RPC
ARG NEXT_PUBLIC_ZKSYNC_SEPOLIA_RPC
ARG NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID
ARG NEXT_PUBLIC_MONEY_CLUBS_SUBGRAPH_API_KEY
ARG NEXT_PUBLIC_JWKS_URI
ARG NEXT_PUBLIC_JWKS_URI_TESTNET
ARG NEXT_PUBLIC_ELIZA_API_URL
ARG MONGO_URI
ARG VENICE_API_KEY
ARG SESSION_SECRET

ENV NEXT_PUBLIC_LAUNCHPAD_CHAIN_ID=${NEXT_PUBLIC_LAUNCHPAD_CHAIN_ID}
ENV NEXT_PUBLIC_ALCHEMY_API_KEY=${NEXT_PUBLIC_ALCHEMY_API_KEY}
ENV NEXT_PUBLIC_POLYGON_RPC=${NEXT_PUBLIC_POLYGON_RPC}
ENV NEXT_PUBLIC_MAINNET_RPC=${NEXT_PUBLIC_MAINNET_RPC}
ENV NEXT_PUBLIC_ZKSYNC_RPC=${NEXT_PUBLIC_ZKSYNC_RPC}
ENV NEXT_PUBLIC_BASE_RPC=${NEXT_PUBLIC_BASE_RPC}
ENV NEXT_PUBLIC_BASE_SEPOLIA_RPC=${NEXT_PUBLIC_BASE_SEPOLIA_RPC}
ENV NEXT_PUBLIC_ZKSYNC_SEPOLIA_RPC=${NEXT_PUBLIC_ZKSYNC_SEPOLIA_RPC}
ENV NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID=${NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID}
ENV NEXT_PUBLIC_MONEY_CLUBS_SUBGRAPH_API_KEY=${NEXT_PUBLIC_MONEY_CLUBS_SUBGRAPH_API_KEY}
ENV NEXT_PUBLIC_JWKS_URI=${NEXT_PUBLIC_JWKS_URI}
ENV NEXT_PUBLIC_JWKS_URI_TESTNET=${NEXT_PUBLIC_JWKS_URI_TESTNET}
ENV NEXT_PUBLIC_ELIZA_API_URL=${NEXT_PUBLIC_ELIZA_API_URL}
ENV MONGO_URI=${MONGO_URI}
ENV VENICE_API_KEY=${VENICE_API_KEY}
ENV SESSION_SECRET=${SESSION_SECRET}


RUN pnpm build

FROM base AS runner
WORKDIR /app

ENV NODE_ENV=production

COPY --from=builder /app/public ./public

COPY --from=builder --chown=node:node /app/.next ./.next
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./package.json

COPY --from=builder --chown=node:node /app/.next/standalone ./
COPY --from=builder --chown=node:node /app/.next/static ./.next/static


USER node

EXPOSE 3000

ENV PORT 3000

CMD ["pnpm", "start"] 